### ISSUE TITLE
Update to ParadeDB 0.11.0

### ISSUE THREAD

**Issue by philippemnoel** [ShabuShabu/laravel-paradedb-search#3]
### What happened?

Hi Boris :) We stabilized our API on the `@@@` operator in `v0.11.0`, and have deprecated the old `.search` API. You can see the changelog here: https://docs.paradedb.com/changelog/0.11.0.

Would love for you to update the Laravel package to the new syntax and we'd be happy to help advertise it!

### How to reproduce the bug

N/A

### Package Version

N/A

### PHP Version

N/A

### Laravel Version

N/A

### Notes

Thank you Boris!

**Comment by boris-glumpler** [comment]
Hey Phil,

thanks for the reminder! Updating the package to work with the latest release of `pg_search` is already on my todo list. I've been traveling the last couple months in Pakistan, tho, and left all my work stuff in India. I'll be back in about a week, so will be able to look into it then!

Cheers!

**Comment by boris-glumpler** [comment]
Love the changes, btw! Feels way more intuitive. Adding custom operators isn't currently supported in Laravel, tho, if I remember correctly. Might make the update a bit tricky.

**Comment by boris-glumpler** [comment]
Cannot create the extension on the test db atm: https://github.com/paradedb/paradedb/issues/1920

**Comment by boris-glumpler** [comment]
Just pushed the latest v0.12.0-compatible code with test coverage at 95%.
